### ISSUE TITLE
for some reason EventCard components are not being shown in EventList page/component while using axios.

### ISSUE THREAD

**Issue by ssoumyajit** [Code-Pop/real-world-vue#11]
I followed the lessons carefully. But When I made the API call using axios from a dummy database (db.json) I don't see the events on the EventList page. I did not use any style as mention in the lessons. Also created a very small API just for testing purpose.

db.json:
`{
  "events":[
      {
          "id": 1,
          "title": "StreetVibez"
      },
      {
          "id": 2,
          "title": "BuildItUp"
      },
      {
          "id": 3,
          "title": "RandomCircle"
      }
  ]
}
`
EventsList.vue:

`<template>
  <div>
    <h4>Events Listing</h4>
    <EventCard v-for = "event in events" :key = "event.id" :event="event"/>
         
    
  </div>
    
</template>

<script>
import EventCard from '@/components/EventCard.vue'
import EventService from '@/services/EventService.js'

// first we export this component to DOM !!
// now we write some code which will help us to register EventCard component
// as a child component of Event List
export default {       
  components: {
    EventCard
  },

  //let's use the api data inside our component..so we create a reactive property
  //called events
  data() {
    return {
      events: []
    }
  },
  created() {
    EventService.getEvents()
    .then(response => {
      this.events = response.data
    })
    .catch(error => {
      console.log('There was an error:', error.response)
    })
  }
}
</script>
`
EventCard.vue:
`<template>
  <router-link :to="{ name: 'event-show', params: { id: event.id } }" >
    <div>
        <h4>{{ event.title }}</h4>
    </div>
  </router-link>
</template>

<script>
    export default {
        props: {
            event: Object   // important **object vs 0bject **
        }
    }
</script>

<style scoped>
h4 {
    color:green;
}

</style>`

![Screenshot 2019-09-11 13 07 03](https://user-images.githubusercontent.com/35195382/64669690-248dd000-d495-11e9-8e51-bb16c856a03a.png)

**Comment by ssoumyajit** [comment]
I followed the lessons carefully. But When I made the API call using axios from a dummy database (db.json) I don't see the events on the EventList page. I did not use any style as mention in the lessons. Also created a very small API just for testing purpose. 

db.json:

`{
  "events":[
      {
          "id": 1,
          "title": "StreetVibez"
      },
      {
          "id": 2,
          "title": "BuildItUp"
      },
      {
          "id": 3,
          "title": "RandomCircle"
      }
  ]
}
`
EventList.vue:
`<template>
  <div>
    <h4>Events Listing</h4>
    <EventCard v-for = "event in events" :key = "event.id" :event="event"/>
         
    
  </div>
    
</template>

<script>
import EventCard from '@/components/EventCard.vue'
import EventService from '@/services/EventService.js'

// first we export this component to DOM !!
// now we write some code which will help us to register EventCard component
// as a child component of Event List
export default {       
  components: {
    EventCard
  },

  //let's use the api data inside our component..so we create a reactive property
  //called events
  data() {
    return {
      events: []
    }
  },
  created() {
    EventService.getEvents()
    .then(response => {
      this.events = response.data
    })
    .catch(error => {
      console.log('There was an error:', error.response)
    })
  }
}
</script>
`
EventCard.vue:
`<template>
  <router-link :to="{ name: 'event-show', params: { id: event.id } }" >
    <div>
        <h4>{{ event.title }}</h4>
    </div>
  </router-link>
</template>

<script>
    export default {
        props: {
            event: Object   // important **object vs 0bject **
        }
    }
</script>

<style scoped>
h4 {
    color:green;
}


</style>`
![Screenshot 2019-09-11 12 02 18](https://user-images.githubusercontent.com/35195382/64667334-12f3fa80-d48c-11e9-8deb-ed1815d20a26.png)

**Comment by Second-Place** [comment]
Can you show the logs?
